apiVersion: v1
kind: ConfigMap
metadata:
 name: pgadmin-config
 namespace: example
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "PostgreSQL Database",
           "Group": "Servers",
           "Port": 5432,
           "Username": "robin",
           "Host": "postgres.example.svc.cluster.local",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
         }
       }
   }